apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: cockpitpro.azurecr.io/cockpit_be:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: cockpitbackendenv
        ports:
        - containerPort: 4000
        resources: {}
      imagePullSecrets:
      - name: acrlogincockpitpro
