apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment2
  namespace: gitlab-runner
spec:
  selector:
    matchLabels:
      app: sqlserver
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver-container2
        image: prashantshivach/sqlserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql/
          name: mysql-volume
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: MYAPP
              key: DB_HOST
      volumes:
      - name: mysql-volume-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc

