name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Navigate to SignUp-mysql directory
      run: cd ./SignUp-mysql && ls
      
      
    - name: List files in the directory
      run: ls

    - name: Build Docker image
      run: |
       cd ./SignUp-mysql && ls
       docker build . -t cockpitpro.azurecr.io/cockpit_be:latest

    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: 'cockpitpro.azurecr.io'
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Push Image to ACR
      run: |
        docker push cockpitpro.azurecr.io/cockpit_be:latest

    

  # deploy:
  #   runs-on: ubuntu-latest

  #   needs: build

  #   steps:
  #   - name: Install SSH
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.VM_HOST }}
  #       username: ${{ secrets.VM_USERNAME }}
  #       password: ${{ secrets.VM_PASSWORD }}
  #       script: |
  #         sudo docker pull rupali1520/cockpit-backend:prod
  #         sudo docker stop cockpit-backend
  #         sudo docker rm -f cockpit-backend
  #         sudo docker run -dp 4000:4000 --name cockpit-backend rupali1520/cockpit-backend:prod
