name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Navigate to SignUp-mysql directory
      run: cd ./SignUp-mysql && ls
      
      
    - name: List files in the directory
      run: ls

    - name: Build Docker image
      run: |
       cd ./SignUp-mysql && ls
       docker build -t rupali1520/cockpit-backend:1 .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push rupali1520/cockpit-backend:1

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Install SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          docker pull rupali1520/cockpit-backend:1
          docker run rupali1520/cockpit-backend:1
